import argparse
import json
import sys
from pathlib import Path
from typing import Any

SCRIPT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPT_ROOT / "script_experiment"))

from evaluate_face_detections import bbox_iou


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Post-filter SCRFD/MediaPipe detection JSON to reduce duplicate and tiny detections."
    )
    parser.add_argument(
        "--predictions",
        type=Path,
        required=True,
        help="Input prediction JSON generated by run_scrfd_mediapipe.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Filtered prediction JSON output path.",
    )
    parser.add_argument(
        "--min-box-size",
        type=float,
        default=0.0,
        help="Minimum sqrt(width*height) in pixels. Default: 0.",
    )
    parser.add_argument(
        "--post-nms-iou",
        type=float,
        default=None,
        help="Optional second-pass NMS IoU threshold after size filtering.",
    )
    parser.add_argument(
        "--max-detections",
        type=int,
        default=None,
        help="Optional maximum detections per image after sorting by score.",
    )
    parser.add_argument(
        "--require-mediapipe-eyes",
        action="store_true",
        help="Drop detections where MediaPipe did not return eye landmarks.",
    )
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as file:
        return json.load(file)


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(data, file, ensure_ascii=False, indent=2)
        file.write("\n")


def box_size(detection: dict[str, Any]) -> float:
    bbox = detection["bbox"]
    width = max(0.0, float(bbox.get("width", float(bbox["xbr"]) - float(bbox["xtl"]))))
    height = max(0.0, float(bbox.get("height", float(bbox["ybr"]) - float(bbox["ytl"]))))
    return (width * height) ** 0.5


def second_pass_nms(detections: list[dict[str, Any]], iou_threshold: float) -> list[dict[str, Any]]:
    kept = []
    for detection in sorted(detections, key=lambda item: item.get("score", 0.0), reverse=True):
        if all(bbox_iou(detection["bbox"], existing["bbox"]) < iou_threshold for existing in kept):
            kept.append(detection)
    return kept


def filter_detections(
    predictions: dict[str, Any],
    min_box_size: float,
    post_nms_iou: float | None,
    max_detections: int | None,
    require_mediapipe_eyes: bool,
) -> dict[str, Any]:
    before = 0
    after = 0
    output = {
        **predictions,
        "records": [],
        "post_filter": {
            "min_box_size": min_box_size,
            "post_nms_iou": post_nms_iou,
            "max_detections": max_detections,
            "require_mediapipe_eyes": require_mediapipe_eyes,
        },
    }

    for record in predictions.get("records", []):
        detections = list(record.get("detections", []))
        before += len(detections)
        filtered = []
        for detection in detections:
            if box_size(detection) < min_box_size:
                continue
            if require_mediapipe_eyes and not detection.get("mediapipe_eye_landmarks"):
                continue
            filtered.append(detection)
        if post_nms_iou is not None:
            filtered = second_pass_nms(filtered, post_nms_iou)
        filtered = sorted(filtered, key=lambda item: item.get("score", 0.0), reverse=True)
        if max_detections is not None:
            filtered = filtered[:max_detections]
        after += len(filtered)
        output["records"].append({**record, "detections": filtered})

    output["post_filter"]["detections_before"] = before
    output["post_filter"]["detections_after"] = after
    output["post_filter"]["removed_detections"] = before - after
    return output


def main() -> int:
    args = parse_args()
    if args.min_box_size < 0.0:
        raise ValueError("--min-box-size must be non-negative.")
    if args.post_nms_iou is not None and not 0.0 <= args.post_nms_iou <= 1.0:
        raise ValueError("--post-nms-iou must be between 0 and 1.")
    if args.max_detections is not None and args.max_detections <= 0:
        raise ValueError("--max-detections must be positive.")

    predictions = load_json(args.predictions)
    filtered = filter_detections(
        predictions,
        min_box_size=args.min_box_size,
        post_nms_iou=args.post_nms_iou,
        max_detections=args.max_detections,
        require_mediapipe_eyes=args.require_mediapipe_eyes,
    )
    write_json(args.output, filtered)
    stats = filtered["post_filter"]
    print(f"output: {args.output}")
    print(f"detections_before: {stats['detections_before']}")
    print(f"detections_after: {stats['detections_after']}")
    print(f"removed_detections: {stats['removed_detections']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
